im1 = imread("C:\Users\CSLab\dip shruti\b&w.jpg")
subplot(2,2,1)
title("ORIGINAL")
imshow(im1)
se = imcreatese('rect', 10,10)
img2 = imerode(im1, se)
subplot(2,2,2)
title("Erode")
imshow(img2)
img3 = imdilate(im1, se)
subplot(2,2,3)
title("DILATE")
imshow(img3)
se1 = imcreatese('cross', 20,20)
img4 = imerode(im1, se1)
subplot(2,2,4)
title("Erode 1")
imshow(img4);
